name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0" 

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  novident_corkboard:
    path: ../
  novident_nodes:
    git:
      url: https://github.com/Novident/novident-nodes.git
      ref: master
  appflowy_editor: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

