name: novident_corkboard
description: "Novident's Corkboard is a visual board with tiles that represents the entities that you want, allowing you to easily rearrange them to give structure to your writing"
version: 1.0.0
homepage: https://github.com/Novident/novident-corkboard
issue_tracker: https://github.com/Novident/novident-corkboard/issues/
documentation: https://github.com/Novident/novident-corkboard

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.16.0
  collection: ^1.19.1
  novident_nodes:
    git:
      url: https://github.com/Novident/novident-nodes.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

